# Generated by Django 5.1.7 on 2025-03-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_description', models.TextField(max_length=90)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
