# Generated by Django 5.1.7 on 2025-03-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_image',
            field=models.ImageField(default='default.jpg', upload_to='productsimg'),
        ),
    ]
