# Generated by Django 5.1.7 on 2025-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_products_p_stock_category_products_p_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_costprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
