# Generated by Django 5.1.7 on 2025-04-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_products_p_costprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
