# Generated by Django 5.1.7 on 2025-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_products_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_description',
            field=models.TextField(max_length=200),
        ),
    ]
